### ISSUE TITLE
Missing dependancies.

### ISSUE THREAD

**Issue by DDR-Khat** [Reimnop/Discord4Fabric#2]
Aside from JDA, additional dependencies are missing causing additional boot-up failures.

`[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'd4f'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.6.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [bitboxed-fabric-server-mc.1.19.jar:0.11.0]
Caused by: java.lang.NoClassDefFoundError: okhttp3/RequestBody
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1741) ~[net_dv8tion_jda-5.0.0-alpha.12-82cce463f657b924.jar:?]
	at me.reimnop.d4f.Discord.<init>(Discord.java:30) ~[discord4fabric-1.1.0.jar:?]
	at me.reimnop.d4f.Discord4Fabric.initDiscord(Discord4Fabric.java:53) ~[discord4fabric-1.1.0.jar:?]
	at me.reimnop.d4f.Discord4Fabric.onInitialize(Discord4Fabric.java:43) ~[discord4fabric-1.1.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: okhttp3.RequestBody
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1741) ~[net_dv8tion_jda-5.0.0-alpha.12-82cce463f657b924.jar:?]
	at me.reimnop.d4f.Discord.<init>(Discord.java:30) ~[discord4fabric-1.1.0.jar:?]
	at me.reimnop.d4f.Discord4Fabric.initDiscord(Discord4Fabric.java:53) ~[discord4fabric-1.1.0.jar:?]
	at me.reimnop.d4f.Discord4Fabric.onInitialize(Discord4Fabric.java:43) ~[discord4fabric-1.1.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
	... 8 more
`

**Comment by Reimnop** [comment]
Will be fixed on next release. Thank you for the report!
