### ISSUE TITLE
Unable to start server using latest version

### ISSUE THREAD

**Issue by ChristopherHaws** [Reimnop/Discord4Fabric#38]
Hello,

When upgrading from 1.7.0 to 1.8.0, my Minecraft server no longer starts. This is the exception from the logs:

```
[13:04:12] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'server_translations_api'!
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.1-beta.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) [quilt-loader-0.17.1-beta.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) [quilt-loader-0.17.1-beta.6.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:49) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:112) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:220) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:51) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2477 failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:248) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:48) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:49) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:112) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:220) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:51) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:48) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:49) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:112) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:220) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:51) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for d4f.mixins.json:LanguageMixin during activity: [Transform -> Method lambda$create$0(Ljava/util/function/BiConsumer;Lnet/fabricmc/loader/api/ModContainer;)V -> INVOKEINTERFACE -> net/fabricmc/loader/impl/metadata/LoaderModMetadata::getEntrypoints:(Ljava/lang/String;)Ljava/util/List;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:48) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:49) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:112) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:220) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:51) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.metadata.LoaderModMetadata
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:48) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:49) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:112) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:220) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:51) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.metadata.LoaderModMetadata
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:48) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.14+1.19-rc2.jar-7c9d19ba-5cdb-453d-b678-1a68d94200b4-nested.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:49) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:112) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:220) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:51) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
```

Thanks

**Comment by gadget78** [comment]
rename your `discord4fabric.json` file to something like `discord4fabric.json.old` and restart ... 
see if that helps, then slowly put things back in :)

**Comment by Reimnop** [comment]
Seems like you're using Quilt, and not Fabric. This mod uses some Fabric-specific functionalities from 1.8.0 to load language files from other mods and will not work on Quilt.

**Comment by SulpherStaer** [comment]
Can confirm that the latest version no longer has quilt support. I also have this issue.

Are you planning quilt support? - Because your mod has _all_ the features I like. I'd even be okay with loosing some features if you detect the mod is running in quilt

**Comment by ChristopherHaws** [comment]
@SulpherStaer I switch to [Simple Discord Link](https://www.curseforge.com/minecraft/mc-mods/simple-discord-link-bot-forge-fabric-spigot/files/3840064) which seems to have the same set of features. I may switch back if quilt support is added, but for now this is working for me.

**Comment by Reimnop** [comment]
I can work on Quilt support if I'm interested and have free time on hand. In the meantime this mod only supports Fabric. Sorry for the inconvenience!

**Comment by SulpherStaer** [comment]
![image](https://user-images.githubusercontent.com/5037244/181649158-43e00abd-1df0-4425-b9cf-3b1414d09091.png)
I asked the quilt community about this particular issue. This was their response.


Anyway, thanks for the wonderful mod, and I hope that you will find the interest and free time. Thanks for the speed of replies & fixes.

**Comment by Reimnop** [comment]
Fixed 👍
