### ISSUE TITLE
Compatibility issue 1.19.1 (maybe 1.19.1 quilt)

### ISSUE THREAD

**Issue by SulpherStaer** [Reimnop/Discord4Fabric#39]
```` 
[16:16:27] [JDA MainWS-ReadThread/ERROR]: One of the EventListeners had an uncaught exception
java.lang.NoSuchFieldError: field_11735
        at me.reimnop.d4f.listeners.MinecraftEventListeners.lambda$init$24(MinecraftEventListeners.java:223) ~[discord4fabric-1.7.0.jar:?]
        at me.reimnop.d4f.events.DiscordMessageReceivedCallback.lambda$static$0(DiscordMessageReceivedCallback.java:11) ~[discord4fabric-1.7.0.jar:?]
        at me.reimnop.d4f.listeners.DiscordMessageListener.onMessageReceived(DiscordMessageListener.java:16) ~[discord4fabric-1.7.0.jar:?]
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:361) ~[JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) [JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) [JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) [JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:164) [JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:127) [JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) [JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:957) [JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:844) [JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:822) [JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:996) [JDA-5.0.0-alpha.12.jar-9b4b5e4d-721a-47cf-b67f-f6f56fd239dd-nested.jar:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) [nv-websocket-client-2.14.jar-1d7dd4d8-8027-48ca-beb2-cb083c4cf03f-nested.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) [nv-websocket-client-2.14.jar-1d7dd4d8-8027-48ca-beb2-cb083c4cf03f-nested.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) [nv-websocket-client-2.14.jar-1d7dd4d8-8027-48ca-beb2-cb083c4cf03f-nested.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) [nv-websocket-client-2.14.jar-1d7dd4d8-8027-48ca-beb2-cb083c4cf03f-nested.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [nv-websocket-client-2.14.jar-1d7dd4d8-8027-48ca-beb2-cb083c4cf03f-nested.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [nv-websocket-client-2.14.jar-1d7dd4d8-8027-48ca-beb2-cb083c4cf03f-nested.jar:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) [nv-websocket-client-2.14.jar-1d7dd4d8-8027-48ca-beb2-cb083c4cf03f-nested.jar:?]
````
        
Version 1.7.0 no longer works on 1.19.1 and gives this error when someone sends a chat message in discord.

And the error below is when someone sends a message in minecraft:

```` 
[16:22:03] [Server thread/WARN]: Sulpherstaer sent expired chat: 'test'. Is the client/server system time unsynchronized?
[16:22:03] [Server thread/ERROR]: Chain link failed, continuing to next one
java.lang.AbstractMethodError: Receiver class me.reimnop.d4f.listeners.MinecraftEventListeners$$Lambda$4087/0x00000008017e73f0 does not define or inherit an implementation of the resolved method 'abstract void onChatMessage(net.minecraft.class_7471, net.minecraft.class_3222, net.minecraft.class_2556$class_7602)' of interface net.fabricmc.fabric.api.message.v1.ServerMessageEvents$ChatMessage.
        at net.fabricmc.fabric.api.message.v1.ServerMessageEvents.lambda$static$6(ServerMessageEvents.java:101) ~[fabric-message-api-v1-4.0.0-beta.1+0.58.5-1.19.1.jar-eb77b2de-acdc-4d6f-b0d1-14703ebc4cc5-nested.jar:?]
        at net.minecraft.class_3324.handler$zje000$onSendChatMessage(class_3324.java:1539) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_43673(class_3324.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_44155(class_3244.java:1444) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_45064(class_3244.java:1302) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$znj000$modifiedRunLoop(MinecraftServer.java:5394) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
````

Join / leave & boot messages still work perfectly fine

**Comment by Reimnop** [comment]
Fixed, will push update tomorrow.
