### ISSUE TITLE
[BUGS] Message rate, disconnect detections

### ISSUE THREAD

**Issue by gadget78** [Reimnop/Discord4Fabric#59]
i think ive narrowed down a Bug that leads to crashing MC.. 
with any small connection issues, it will result in cascade event...
where it will initially give errors about not being able to send, 
and then as it cannot send that to console, that will fail, leading to more errors... 
leading to a complete flood of errors in the logs.. 

heres are some highlight of extracts ive found that shows the story .. 
```
[13:30:12] [JDA RateLimit-Worker 5/ERROR]: DNS resolution failed: discord.com: Temporary failure in name resolution
[13:30:12] [ForkJoinPool.commonPool-worker-108/ERROR]: RestAction queue returned failure: [ErrorResponseException] -1: java.net.UnknownHostException discord.com: Temporary failure in name resolution
[13:30:29] [JDA MainWS-ReadThread/WARN]: Reconnect failed! Next attempt in 2s

```
oddly my server is getting plagued with these brief DNS issues ?
(but the other Minecraft docker containers have NO issues with DNS !..)
but this causes a cascade event, that crashes the server, instead of easily recovering 
as all the players never get disconnected at any point, and play along unaware, so i don't understand why i get these occasional DNS issues ? but this 1st brings down the discord bridge, then the server....
other extracts from the MASSIVE logs... 

```
[13:32:12] [Webhook-RateLimit Thread WebhookID: 997266261698428928/ERROR]: There was some error while sending a webhook message java.net.SocketTimeoutException: Connect timed out
[13:38:19] [JDA RateLimit-Worker 2/ERROR]: There was an I/O error while executing a REST request: Connect timed out
An exception occurred processing Appender D4fConsoleMessageListener java.lang.IllegalArgumentException: Provided text for message must be less than 2000 characters in length
```
from that initial 1st error to here, is 5 THOUSAND of mostly repeated lines,
and then from this point there are like PAGES and PAGES of [STDERR] logs, in fact 17 THOUSAND lines !! :(  
(the log file from start to crash, is 8MB !)
which is what i think ultimately makes the server close .. 
```
[13:39:34] [JDA MainWS-ReadThread/WARN]: Got disconnected from WebSocket (Code 1000). Appending to reconnect queue
[13:39:35] [Thread-7/INFO]: [STDERR]: me.reimnop.d4f.exceptions.GuildException: Couldn't find guild with id '900426441357930496'!
[13:39:35] [Thread-7/INFO]: [STDERR]: 	at me.reimnop.d4f.Discord.getConsoleGuild(Discord.java:95)
[13:39:35] [Thread-7/INFO]: [STDERR]: 	at me.reimnop.d4f.Discord.getConsoleChannel(Discord.java:101)
.......
[13:41:42] [JDA MainWS-ReadThread/INFO]: Connected to WebSocket
[13:41:42] [JDA MainWS-ReadThread/INFO]: [STDERR]: me.reimnop.d4f.exceptions.GuildException: Couldn't find guild with id '900426441357930496'!
[13:41:42] [JDA MainWS-ReadThread/INFO]: [STDERR]: at me.reimnop.d4f.Discord.getConsoleGuild(Discord.java:95)
[13:41:43] [JDA MainWS-ReadThread/ERROR]: Got an unexpected error. Please redirect the following message to the devs:
	JDA 5.0.0-alpha.12_edbc423
```

users are still playing along... server gets laggy, then sorta closes, people who are still connected can carry on playing, untill one disconnects, which then makes server shutdown, not sure why it waits for a user to d/c ?
a simple restart of container, will sort it out instantly, for HOURS at a time.. but ultamitaly, i know it may be a small hicup is connection, but it should be able to recover from that, but it cannot as of the complete flood, which just makes the issue MUCH worse.. where it should just be small blip ...

**Comment by gadget78** [comment]
follow up of this issue to confirm some things ... 

with the console disabled, server no longer gets flooded and closes... 
even though i still have some kind of network issue, server now easily recovers from small network outages... 
so its JUST the handling of the console room, on disconnects of websocket etc that needs addressing... 

(i dont have a DNS issue, but as it was spamming and trying to resolve discord.com so much, thats what it reported 1st ... 
so all boils down the sheer amount of messages it was trying to dump to console room, when it couldnt)

**Comment by Reimnop** [comment]
The console channel implementation is quite unclean and haven't been tested well. I haven't had time to fix it yet because I've been really busy. In the meantime I'd advise against using the console feature.
