### ISSUE TITLE
This error has been crashing my server for a long time, i did not realize that it was discord4fabric till now. (bug, of which sometimes crashes server)

### ISSUE THREAD

**Issue by NotFlow69** [Reimnop/Discord4Fabric#69]
**Huge Bug, Which i recommend fixing as it rarely crashes servers. PLEASE FIX!** @Reimnop 

Error Below:

`One of the EventListeners had an uncaught exception>
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3739()" because "server" is null
	at eu.pb4.placeholders.api.PlaceholderContext.of(PlaceholderContext.java:73) ~[Placeholder-api-2.0.0-pre.4+1.19.3.jar:?]
	at eu.pb4.placeholders.api.PlaceholderContext.of(PlaceholderContext.java:69) ~[Placeholder-api-2.0.0-pre.4+1.19.3.jar:?]
	at me.reimnop.d4f.listeners.MinecraftEventListeners.lambda$init$27(MinecraftEventListeners.java:244) ~[Discord4Fabric-1.19.3-1.10.2.jar:?]
	at me.reimnop.d4f.events.DiscordMessageReceivedCallback.lambda$static$0(DiscordMessageReceivedCallback.java:11) ~[Discord4Fabric-1.19.3-1.10.2.jar:?]
	at me.reimnop.d4f.listeners.DiscordMessageListener.onMessageReceived(DiscordMessageListener.java:16) ~[Discord4Fabric-1.19.3-1.10.2.jar:?]
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:361) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:164) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:127) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:957) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:844) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:822) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:996) ~[net_dv8tion_jda-5.0.0-alpha.12-f6fc9a3ea949c79b.jar:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[com_neovisionaries_nv-websocket-client-2.14-34f0b46cffc3021.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[com_neovisionaries_nv-websocket-client-2.14-34f0b46cffc3021.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[com_neovisionaries_nv-websocket-client-2.14-34f0b46cffc3021.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[com_neovisionaries_nv-websocket-client-2.14-34f0b46cffc3021.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[com_neovisionaries_nv-websocket-client-2.14-34f0b46cffc3021.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[com_neovisionaries_nv-websocket-client-2.14-34f0b46cffc3021.jar:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[com_neovisionaries_nv-websocket-client-2.14-34f0b46cffc3021.jar:?]`

**Comment by Reimnop** [comment]
Can't reproduce at the moment. It would be nice if you provide a mod list.

**Comment by NotFlow69** [comment]
How do i provide a mod list?, (im new to github)

**Comment by NotFlow69** [comment]
Oh, you mean all the mods, that i currently have on my server?

How do you want the mods?, the link to the download or the `.jar` files?

**Comment by Reimnop** [comment]
I just need its names.

**Comment by NotFlow69** [comment]
Alright, The Mods Are:

Page 1:
![image](https://user-images.githubusercontent.com/112746855/224034966-d6cd5f6f-28e9-4085-bbe4-56f8b1b52b55.png)

Page 2:
![image](https://user-images.githubusercontent.com/112746855/224035147-b863960a-b6b4-423c-aecb-f44d87e78254.png)

Page 3:
![image](https://user-images.githubusercontent.com/112746855/224035324-d56e7af1-758c-4ea0-9e19-06818b425a91.png)

**Comment by NotFlow69** [comment]
um, i quite did not get it, how do i fix this error?

**Comment by NotFlow69** [comment]
When Will You Fix The Error?

**Comment by NotFlow69** [comment]
Hi, this is just a note: this bug is still affecting the newest dev version and it is crashing servers badly, please fix it.
