### ISSUE TITLE
How do i fix this (Webhook problem) [HELP]

### ISSUE THREAD

**Issue by NotFlow69** [Reimnop/Discord4Fabric#81]
`[11:51:53] [Webhook-RateLimit Thread WebhookID: 1099344371595366482/ERROR]: Sending a webhook message failed with non-OK http response
club.minnced.discord.webhook.exception.HttpException: Request returned failure 404: {"message": "Unknown Webhook", "code": 10015}
        at club.minnced.discord.webhook.WebhookClient.failure(WebhookClient.java:757) ~[club_minnced_discord-webhooks-0.8.0-f9f6b3e1345bf4b0.jar:?]
        at club.minnced.discord.webhook.WebhookClient.executePair(WebhookClient.java:832) ~[club_minnced_discord-webhooks-0.8.0-f9f6b3e1345bf4b0.jar:?]
        at club.minnced.discord.webhook.WebhookClient.drainQueue(WebhookClient.java:801) ~[club_minnced_discord-webhooks-0.8.0-f9f6b3e1345bf4b0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:51:56] [Server thread/INFO]: [Not Secure] <OneLemon54> e
[11:51:56] [Webhook-RateLimit Thread WebhookID: 1099344371595366482/ERROR]: Sending a webhook message failed with non-OK http response
club.minnced.discord.webhook.exception.HttpException: Request returned failure 404: {"message": "Unknown Webhook", "code": 10015}
        at club.minnced.discord.webhook.WebhookClient.failure(WebhookClient.java:757) ~[club_minnced_discord-webhooks-0.8.0-f9f6b3e1345bf4b0.jar:?]
        at club.minnced.discord.webhook.WebhookClient.executePair(WebhookClient.java:832) ~[club_minnced_discord-webhooks-0.8.0-f9f6b3e1345bf4b0.jar:?]
        at club.minnced.discord.webhook.WebhookClient.drainQueue(WebhookClient.java:801) ~[club_minnced_discord-webhooks-0.8.0-f9f6b3e1345bf4b0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

@Reimnop

**Comment by NotFlow69** [comment]
the webhook is correct, copy pasted the link from discord,
why isnt it working?

**Comment by Reimnop** [comment]
Have you checked with other Discord bridge mods like Disfabric?

**Comment by NotFlow69** [comment]
not yet..

**Comment by Reimnop** [comment]
Can you try it to see if it works?
